name: careerpath_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=25.3
  - pip:
    - pandas==2.0.3
    - numpy==1.24.3
    - scikit-learn==1.3.1
    - python-dateutil==2.8.2
    - pyarrow==13.0.0
    - streamlit==1.50.0
    - plotly==5.17.0
    - fsspec==2026.2.0
    - huggingface-hub==0.34.0
    - datasets==2.10.0

