name: careerpath_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas==2.0.3
  - numpy==1.24.3
  - scikit-learn==1.3.1
  - python-dateutil==2.8.2
  - pyarrow==13.0.0
  - streamlit==1.50.0
  - plotly==5.17.0
  - datasets==2.10.0
